# Generated by Django 3.2.22 on 2023-10-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20231028_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='type',
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='exercises',
            field=models.ManyToManyField(to='homeapp.Exercises'),
        ),
        migrations.DeleteModel(
            name='WorkoutPlanTest',
        ),
    ]
