# Generated by Django 3.2.22 on 2023-10-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_auto_20231028_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='muscleGroup',
        ),
        migrations.DeleteModel(
            name='MuscleGroup',
        ),
    ]
