# Generated by Django 3.2.22 on 2023-10-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_auto_20231028_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='split',
            field=models.CharField(default='Full Body', max_length=100),
            preserve_default=False,
        ),
    ]
