# Generated by Django 3.2.22 on 2023-10-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_workoutplan_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='days',
            field=models.CharField(default='Split', max_length=100),
            preserve_default=False,
        ),
    ]
