# Generated by Django 3.2.22 on 2023-10-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_workoutplan_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='muscle_group',
            field=models.CharField(default='Muscle', max_length=255),
            preserve_default=False,
        ),
    ]
