# Generated by Django 3.2.22 on 2023-10-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_exercises_muscle_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='variation',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
