# Generated by Django 3.2.22 on 2023-10-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_workoutplan_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioBtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_radio_field', models.CharField(choices=[('Three Days', 'Three Days'), ('Six Days', 'Six Days')], max_length=50)),
            ],
        ),
    ]
