# Generated by Django 3.2.22 on 2023-10-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_radiobtn'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=100),
            preserve_default=False,
        ),
    ]
