# Generated by Django 3.2.22 on 2023-10-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_workoutplan_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='exercises',
            field=models.ManyToManyField(related_name='workout_plans', to='homeapp.Exercises'),
        ),
    ]
