# Generated by Django 3.2.22 on 2023-11-01 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_alter_workoutplan_exercises'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RadioBtn',
        ),
    ]
