# Generated by Django 3.2.22 on 2023-11-02 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_usercreatedex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercreatedex',
            old_name='description',
            new_name='exercise_description',
        ),
        migrations.RenameField(
            model_name='usercreatedex',
            old_name='name',
            new_name='exercise_name',
        ),
    ]
