# Generated by Django 3.2.22 on 2023-12-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_alter_usercreatedex_muscle_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreatedex',
            name='muscle_group',
            field=models.CharField(choices=[('biceps', 'Biceps'), ('triceps', 'Triceps'), ('shoulders', 'Shoulders'), ('chest', 'Chest'), ('back', 'Back'), ('quadriceps', 'Quadriceps'), ('hamstring', 'Hamstring'), ('calf', 'Calf'), ('abs', 'Abs')], max_length=255),
        ),
    ]
