# Generated by Django 3.2.22 on 2023-12-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0017_alter_usercreatedex_muscle_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreatedex',
            name='muscle_group',
            field=models.CharField(choices=[('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Shoulders', 'Shoulders'), ('Chest', 'Chest'), ('Back', 'Back'), ('Quadriceps', 'Quadriceps'), ('Hamstring', 'Hamstring'), ('Calf', 'Calf'), ('Abs', 'Abs')], max_length=255),
        ),
    ]
